name: Publish Docker image to production

on:
  push:
    branches:
      - feature/test-deploy

jobs:
  build-docker-image:
    runs-on: self-hosted
    name: Push Docker image to Docker Hub
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    envs:
      CONTAINER_NAME: trading-bot
      IMAGE_NAME: trading-bot
      DOCKER_NETWORK: trading-bot-net
      DOCKER_HOSTNAME: bot
      DEPLOY_SSH_PORT: 22
      DEPLOY_SSH_USER: root
      DEPLOY_SSH_HOST: 47.130.45.132
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set env
        id: get_env_runners
        run: |
          echo "$(printenv | sort | egrep '^TELEGRAM_CHAT_ID')" >> $GITHUB_ENV
          echo "$(printenv | sort | egrep '^TELEGRAM_TOKEN')" >> $GITHUB_ENV
          echo "$(printenv | sort | egrep '^API_KEY')" >> $GITHUB_ENV
          echo "$(printenv | sort | egrep '^API_SECRET')" >> $GITHUB_ENV
          echo "$(printenv | sort | egrep '^AMOUNT_USDT')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ secrets.DOCKER_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: '${{ secrets.DOCKER_URL }}/node-app/trading-bot'
      
      - name: Run script file
        run: |
          echo "steps: ${{ toJSON(steps) }}"
          echo
          echo "github: ${{ toJSON(github) }}"
          echo
          echo "secrets: ${{ toJSON(secrets) }}"
          echo
          echo "Runner: ${{ toJSON(env) }}"
          echo
        shell: bash

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TELEGRAM_CHAT_ID=${{ env.TELEGRAM_CHAT_ID }}
            TELEGRAM_TOKEN=${{ env.TELEGRAM_TOKEN}}
            API_KEY=${{ env.API_KEY }}
            API_SECRET=${{ env.API_SECRET }}
            AMOUNT_USDT=${{ env.AMOUNT_USDT }}

      - name: SSH to Server and Update Docker Container
        run: |
          DEPLOY_BASH_SCRIPT="echo ${{ secrets.DOCKER_USERNAME }} | docker login ${{ secrets.DOCKER_URL }} --username ${{ secrets.DOCKER_USERNAME }} --password-stdin \
          && docker pull ${{ steps.meta.outputs.tags }} \
          && if [ \"\$(docker ps -q -af name=${{ env.CONTAINER_NAME }})\" ]; then docker rm -f ${{ env.CONTAINER_NAME }}; fi \
          && if [[ ! \"\$(docker images -q ${{ env.IMAGE_NAME }} 2> /dev/null)\" == \"\" ]]; then docker rmi -f ${{ env.IMAGE_NAME }}; fi \
          && docker tag \$(docker image inspect -f '{{ .ID }}' ${{ steps.meta.outputs.tags }}:latest) ${{ env.IMAGE_NAME }} \
          && if ! docker network inspect ${{ env.DOCKER_NETWORK }} >/dev/null 2>&1; then echo \"Network '${{ env.DOCKER_NETWORK }}' does not exist. Creating...\" && docker network create ${{ env.DOCKER_NETWORK }} && sleep 2; fi \
          && docker run --restart always --hostname ${{ env.DOCKER_HOSTNAME }} --name ${{ env.CONTAINER_NAME }} --env-file /opt/trading-bot/.env -d --network ${{ env.DOCKER_NETWORK }} ${{ env.IMAGE_NAME }} \
          && sleep $TIME_PERIOD \
          && echo y | docker system prune \
          && echo y | docker volume prune \
          && exit"
          ssh -oPasswordAuthentication=no \
            -oUserKnownHostsFile=/dev/null \
            -oStrictHostKeyChecking=no \
            -p ${{ env.DEPLOY_SSH_PORT }} ${{ env.DEPLOY_SSH_USER }}@${{ env.DEPLOY_SSH_HOST }} $DEPLOY_BASH_SCRIPT
        shell: sh